### ISSUE TITLE
Just creating this db

### ISSUE THREAD

**Issue by tincancrab** [drawpile/listserver#1]
Been struggling with the guide forever. it wont let me import createdb.sql either

`[liz@syntheticdreams listserver]$ psql listing < doc/createdb.sql
NOTICE:  CREATE TABLE will create implicit sequence "sessions_id_seq" for serial column "sessions.id"
ERROR:  type "boolea" does not exist
LINE 19:  private BOOLEA NOT NULL DEFAULT FALSE
`

**Comment by tincancrab** [comment]
Read the issue, Modified the sql file. No errors, so i'll be moving on to the next step.

current: 
`	roomcode VARCHAR(16) DEFAULT NULL CONSTRAINT unique_roomcode UNIQUE,
	private BOOLEA NOT NULL DEFAULT FALSE
);`

fix:
`	roomcode VARCHAR(16) DEFAULT NULL CONSTRAINT unique_roomcode UNIQUE,
	private BOOLEAN NOT NULL DEFAULT FALSE
);`

**Comment by callaa** [comment]
Thanks for letting me know. I fixed the typo in the script.
