### ISSUE TITLE
NSFW session can't list at pub.drawpile.net

### ISSUE THREAD

**Issue by neiriod** [drawpile/listserver#4]
![02](https://user-images.githubusercontent.com/49644585/75101173-5cd43580-5613-11ea-9073-3e9ef05f86f1.PNG)

the session can't list at pub.drawpile.net if the box of age restricted content is checked

**Comment by Wade821** [comment]
This has been confirmed as an issue by @notfood with the new listing server.

**Comment by callaa** [comment]
Should be fixed now. Please re-open if the issue persists at pub.drawpile.net
