### ISSUE TITLE
Aliased sessions create double entry

### ISSUE THREAD

**Issue by notfood** [drawpile/listserver#5]
To reproduce merely host a session in pub.drawpile.net with an alias. Upon checking it'll be listed twice in the listserver, the urls will each be one with the alias and the other with the real id.

![image](https://user-images.githubusercontent.com/5370107/75294724-26571000-57f7-11ea-8669-a2cba2d3ecaf.png)

![image](https://user-images.githubusercontent.com/5370107/75294803-4e467380-57f7-11ea-91f5-3826cb4b2ce5.png)

**Comment by tincancrab** [comment]
This was introduced recently, as my listserver from the beginning of February cannot reproduce this error.

**Comment by callaa** [comment]
It's caused by my recent (near) rewrite for sure. Currently, I can see one duplicate, the other one is listed by ID and the other by alias.

**Comment by callaa** [comment]
It was indeed the session aliases that were causing this problem. The "fetch from server" listing used only session IDs, while manual announcement used aliases (if set.)
